GET http://localhost:5000/users

###
GET http://localhost:5000/users/1

###

POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "muhammad sidiq firdaus",
    "email": "msg@gmail.com",
    "gender": "Laki"
}

###
PATCH http://localhost:5000/users/1
Content-Type: application/json

{
    "name": "Firdaus",
    "email": "sidiq@gmail.com",
    "gender": "Laki-Laki"
}

###
DELETE http://localhost:5000/users/3